source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'JDStatusBarNotification'
pod 'pop', '~> 1.0'
pod 'FXBlurView', '~> 1.6'
pod 'XMLDictionary', '~> 1.4'
pod 'FlurrySDK/FlurrySDK'
pod 'Parse', '~> 1.6'
pod 'Mixpanel', '~> 2.7'
pod 'KSReachability'
pod 'NewRelicAgent'
pod 'ParseCrashReporting'
pod 'Google/Analytics'
pod 'Lock', '~> 1.12'
pod 'JWTDecode', '~> 0.2'
pod 'Lock-Facebook', '~> 2.0'
pod 'Lock-Twitter', '~> 1.0'

link_with ['KPCC', 'KPCCTests']
