source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'JDStatusBarNotification'
pod 'pop', '~> 1.0'
pod 'FXBlurView', '~> 1.6'
pod 'XMLDictionary', '~> 1.4'
pod 'FlurrySDK'
pod 'Parse'
pod 'Mixpanel'
pod 'TestFlightSDK'
pod 'KSReachability'
pod 'Kochava'

link_with ['KPCC', 'KPCC-TestFlight']
