opt_out_usage

fastlane_version "1.57.0"

default_platform :ios

platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end

  desc "Reset Simulator"
  lane :simreset do
    sh "osascript -e 'tell application \"Simulator\" to quit'"
    sh "xcrun simctl erase all"
  end

  desc "Runs all the tests"
  lane :test do |options|
    scan(scheme: "KPCC", device: options[:device])
    simreset if options[:simreset]
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_branch(branch: 'develop')
    gym(scheme: "KPCC-Release")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    ensure_git_branch(branch: 'develop')
    gym(scheme: "KPCC-Release")
    deliver(force: true)
  end

  after_all do |lane|
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

end
