opt_out_usage

fastlane_version "1.57.0"

default_platform :ios

platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    path = File.expand_path "../Pods", File.dirname(__FILE__)
    cocoapods if Dir["#{path}/*"].empty?
  end

  private_lane :delete_ipa do |options|
    path = options[:path]
    if File.extname(path) == '.ipa'
      File.delete path if File.exist? path
      path.sub! /\.ipa$/, '.app.dSYM.zip'
      File.delete path if File.exist? path
    end
  end

  desc "Reset Simulator"
  lane :simreset do
    sh "osascript -e 'tell application \"Simulator\" to quit'"
    sh "xcrun simctl erase all"
  end

  desc "Runs all the tests"
  lane :test do |options|
    scan(scheme: "KPCC", device: options[:device])
    simreset if options[:simreset]
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_branch(branch: 'develop')
    path = gym(scheme: "KPCC-Release")
    pilot
    delete_ipa(path: path)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    ensure_git_branch(branch: 'develop')
    path = gym(scheme: "KPCC-Release")
    deliver(force: true)
    delete_ipa(path: path)
  end

  after_all do |lane|
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

end
